name: Feature request
description: Suggest an idea for this project.
title: "[REQUEST]: "
labels: 
  - enhancement
assignees: 
  - karasusan
body: 
  - type: markdown
    attributes:
      value: |
        Please check below before post your issue.
        * For questions, ask in [Unity Forum](https://forum.unity.com/forums/unity-render-streaming.413).
        * Before you file an issue read the [Contributing guide](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/CONTRIBUTING.md).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/Unity-Technologies/UnityRenderStreaming/issues).
         
        Please note the following points.
        * We try to reply as soon as possible but we will get in touch with you within **5 working days**.
        * If you solved the issue yourself, please **post the comment and close your issue**.
        * We would close the issue if we do not receive a reply for more than **2 weeks**.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: |
        A clear and concise description of what the problem is. 
        Ex. I'm always frustrated when [...]
      value: |
        I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
      placeholder: |
        Drag and drop image or text files here.
    validations:
      required: false